export interface StandardExercise {
  id: string;
  name: string;
  category: 'Barbell' | 'Dumbbell' | 'Machine' | 'Cable' | 'Bodyweight';
  muscleGroup: 'Chest' | 'Back' | 'Legs' | 'Shoulders' | 'Arms' | 'Core';
  isCompound: boolean;
  defaultWeightKg: number;
  defaultReps: number;
}

export const STANDARD_EXERCISES: StandardExercise[] = [
  // Compound Movements
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    category: 'Barbell',
    muscleGroup: 'Chest',
    isCompound: true,
    defaultWeightKg: 80,
    defaultReps: 6,
  },
  {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    category: 'Barbell',
    muscleGroup: 'Legs',
    isCompound: true,
    defaultWeightKg: 100,
    defaultReps: 5,
  },
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    category: 'Barbell',
    muscleGroup: 'Back',
    isCompound: true,
    defaultWeightKg: 120,
    defaultReps: 5,
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press (OHP)',
    category: 'Barbell',
    muscleGroup: 'Shoulders',
    isCompound: true,
    defaultWeightKg: 50,
    defaultReps: 6,
  },
  {
    id: 'barbell-row',
    name: 'Barbell Bent-Over Row',
    category: 'Barbell',
    muscleGroup: 'Back',
    isCompound: true,
    defaultWeightKg: 70,
    defaultReps: 8,
  },
  {
    id: 'incline-dumbbell-bench-press',
    name: 'Incline Dumbbell Bench Press',
    category: 'Dumbbell',
    muscleGroup: 'Chest',
    isCompound: true,
    defaultWeightKg: 28,
    defaultReps: 8,
  },
  {
    id: 'pull-ups',
    name: 'Pull-Up',
    category: 'Bodyweight',
    muscleGroup: 'Back',
    isCompound: true,
    defaultWeightKg: 0,
    defaultReps: 8,
  },
  {
    id: 'dips',
    name: 'Parallel Bar Dips',
    category: 'Bodyweight',
    muscleGroup: 'Chest',
    isCompound: true,
    defaultWeightKg: 0,
    defaultReps: 10,
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'Machine',
    muscleGroup: 'Legs',
    isCompound: true,
    defaultWeightKg: 160,
    defaultReps: 10,
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift (RDL)',
    category: 'Barbell',
    muscleGroup: 'Legs',
    isCompound: true,
    defaultWeightKg: 80,
    defaultReps: 8,
  },

  // Isolation & Accessory Movements
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    category: 'Dumbbell',
    muscleGroup: 'Shoulders',
    isCompound: false,
    defaultWeightKg: 12,
    defaultReps: 12,
  },
  {
    id: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    category: 'Dumbbell',
    muscleGroup: 'Arms',
    isCompound: false,
    defaultWeightKg: 14,
    defaultReps: 10,
  },
  {
    id: 'tricep-rope-pushdown',
    name: 'Tricep Rope Pushdown',
    category: 'Cable',
    muscleGroup: 'Arms',
    isCompound: false,
    defaultWeightKg: 25,
    defaultReps: 12,
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: 'Machine',
    muscleGroup: 'Legs',
    isCompound: false,
    defaultWeightKg: 50,
    defaultReps: 12,
  },
  {
    id: 'hamstring-curl',
    name: 'Lying Hamstring Curl',
    category: 'Machine',
    muscleGroup: 'Legs',
    isCompound: false,
    defaultWeightKg: 45,
    defaultReps: 12,
  },
  {
    id: 'cable-chest-fly',
    name: 'Cable Chest Fly',
    category: 'Cable',
    muscleGroup: 'Chest',
    isCompound: false,
    defaultWeightKg: 15,
    defaultReps: 12,
  },
  {
    id: 'face-pull',
    name: 'Cable Face Pull',
    category: 'Cable',
    muscleGroup: 'Shoulders',
    isCompound: false,
    defaultWeightKg: 22.5,
    defaultReps: 15,
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raise',
    category: 'Machine',
    muscleGroup: 'Legs',
    isCompound: false,
    defaultWeightKg: 70,
    defaultReps: 15,
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'Bodyweight',
    muscleGroup: 'Core',
    isCompound: false,
    defaultWeightKg: 0,
    defaultReps: 12,
  },
  {
    id: 'ez-bar-preacher-curl',
    name: 'EZ-Bar Preacher Curl',
    category: 'Barbell',
    muscleGroup: 'Arms',
    isCompound: false,
    defaultWeightKg: 30,
    defaultReps: 10,
  }
];
